# core/telemetry/constants.py
"""
Telemetry constants – packet format, team ID, field definitions.
"""
TEAM_ID = "2026-INSPACe-CAN-7USAT-036"

FIELD_NAMES = [
    "TEAM_ID", "TIME_STAMPING", "PACKET_COUNT",
    "ALTITUDE", "PRESSURE", "TEMP", "VOLTAGE",
    "GNSS_TIME", "GNSS_LATITUDE", "GNSS_LONGITUDE", "GNSS_ALTITUDE", "GNSS_SATS",
    "ACCEL_R", "ACCEL_P", "ACCEL_Y",
    "GYRO_R", "GYRO_P", "GYRO_Y",
    "FLIGHT_STATE",
    "HUMIDITY", "UV_INDEX", "LIGHT_INTENSITY", "ROTOR_RPM",
    "MAG_R", "MAG_P", "MAG_Y",
    "MODE", "CMD_ECHO"
]

FLOAT_FIELDS = {
    "ALTITUDE", "PRESSURE", "TEMP", "VOLTAGE",
    "GNSS_ALTITUDE", "GNSS_LATITUDE", "GNSS_LONGITUDE",
    "ACCEL_R", "ACCEL_P", "ACCEL_Y",
    "GYRO_R", "GYRO_P", "GYRO_Y",
    "HUMIDITY", "UV_INDEX", "LIGHT_INTENSITY", "ROTOR_RPM",
    "MAG_R", "MAG_P", "MAG_Y",
}
INT_FIELDS = {"PACKET_COUNT", "GNSS_SATS"}

FLIGHT_STATES = [
    "BOOT", "TEST_MODE", "LAUNCH_PAD", "ASCENT",
    "PRIMARY_DEPLOY", "DESCENT", "SECONDARY_DEPLOY", "IMPACT", "RECOVERY"
]

CMD_TELEMETRY_ON = "CXON"
CMD_TELEMETRY_OFF = "CXOFF"
CMD_CALIBRATE = "CAL"